### ISSUE TITLE
Making Decisions

### ISSUE THREAD

**Issue by erikacamilleri** [stedwardscollegemt/code-games-in-python#4]
Before getting into more complex problem-solving you should be comfortable with the basics. We have prepared some easy exercises for you to practice logical statements in Python.

### Step 1. Open your project in Visual Studio Code

Open Visual Studio Code and navigate to `File > Open Folder`. Find **your code folder** on the **school server** which is the **Z drive**. 

### Step 2. Create another New folder

This chapter is very long, and it is split into different parts. In the next few lessons, you will be creating simple variables to store different types of data in your program. Create a folder called **_making_decisions_**.

### Step 3. Create New files

Inside the folder you just created open the context menu again but this time select `New File` and call it  **_example.py_**. In the working area of the IDE you should see an empty text editor in a tab.

Repeat the process for the following files:
- branching.py
- level_up.py
- monster_and_coins.py

### Step 4. Copy over the code from GitHub

Find all the [code files on GitHub](https://github.com/stedwardscollegemt/code-games-in-python/tree/main/ch02_learning_basics/making_decisions) and for each, copy over the code carefully. 

![image](https://github.com/stedwardscollegemt/code-games-in-python/assets/14978900/6f1016e7-7924-481c-8176-32c868186788)

### Step 5. Go through the lesson slides

Engage in the class discussion so that you will have a good background before diving into the code. 

### Step 6. Complete the TODOs during a Lesson Challenge

You know the drill now. Find comments that start with ` # todo: ` and get some practice.

Have fun!

**Comment by ItsVenomous** [comment]
**Hello!**
